"""create sessions targets images

Revision ID: 2cdecbb237df
Revises: 
Create Date: 2026-10-06 17:46:54.534696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cdecbb237df'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('observing_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('night_of', sa.Date(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('night_of')
    )
    op.create_table('target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('preview_path', sa.String(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exposure_s', sa.Double(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('sharpness', sa.Double(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['observing_session.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    op.create_index(op.f('ix_image_captured_at'), 'image', ['captured_at'], unique=False)
    op.create_index('ix_image_metadata_gin', 'image', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_image_session_id'), 'image', ['session_id'], unique=False)
    op.create_index(op.f('ix_image_sharpness'), 'image', ['sharpness'], unique=False)
    op.create_index(op.f('ix_image_target_id'), 'image', ['target_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_target_id'), table_name='image')
    op.drop_index(op.f('ix_image_sharpness'), table_name='image')
    op.drop_index(op.f('ix_image_session_id'), table_name='image')
    op.drop_index('ix_image_metadata_gin', table_name='image', postgresql_using='gin')
    op.drop_index(op.f('ix_image_captured_at'), table_name='image')
    op.drop_table('image')
    op.drop_table('target')
    op.drop_table('observing_session')
    # ### end Alembic commands ###
